name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove unnecessary files
      run: |
        rm -rf ./.deployment
        rm -rf ./.git*
        rm -rf ./.vscode
        rm -rf ./README.md
    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1.4.8
      with:
        app-name: func-twitterbot-dev-westus2-2b7da17c
        publish-profile: ${{ secrets.DEV_AZURE_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: ''
        enable-oryx-build: ''
